### PR TITLE
fix routes

### LINKED ISSUE #611: Fix sign in page while holding page is active

### PR DESCRIPTION
**Pull request by dlouise64**
# What has changed and why?

Sign in page is now accessible from inside the admin.
closes #611

# How to test this change

- [ ] has automated tests
- [ ] at least one a reviewer ran the code
- [ ] tested in small screen
- [ ] tested in Chrome
- [ ] tested in Firefox
- [ ] tested in IE
- [ ] tested in Safari
- [ ] i18n
- [ ] tested in screen reader/contrast <-- remove this if no UX change

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -26,16 +26,10 @@ class App extends React.Component {
...
-            </main>
-            :
-            <main>
-              <Route exact path="/" component={WizardForm} />
-              <Route path="/:id" component={Sign}/>
-            </main>
-          }
+          <main>
+            <Route exact path="/" component={WizardForm} />
+            <Route path="/:id" component={Sign}/>
```
Comment (Br3nda) [inline src/index.js]: How about instead moving the sign route out of the if statement? Then we have a holding page by default, but the sign path still works
